def add_numbers(number_one: int, number_two: int):
    num_sum = number_one + number_two
    print(num_sum)
    return num_sum


add_numbers(1, 5)
add_numbers(1, 6)

"""
We fixed it!

If you haven't tried yet, try changing the second number back to "Jeff" and you should see a warning. 

Some languages like Python will still let you run at your own peril, even if it's wrong.

In languages like Java and Go, it will refuse to run until you fix your crap.
"""
